import type { AppData } from './types'
import { dateOffset } from './utils'

export function createSeedData(): AppData {
  return {
    employees: [
      { id: 'emp-avery', name: 'Avery Johnson', role: 'Senior Bookkeeper' },
      { id: 'emp-jordan', name: 'Jordan Ellis', role: 'Bookkeeper' },
      { id: 'emp-patrice', name: 'Patrice Bell', role: 'Owner' },
    ],
    clients: [
      {
        id: 'client-clover',
        name: 'Clover Ridge Dental',
        contact: 'Dr. Maya Kent',
        billingMode: 'hourly',
        hourlyRate: 145,
        planId: null,
        assignedEmployeeIds: ['emp-avery'],
        email: 'billing@cloverridgedental.example',
        contactName: 'Dr. Maya Kent',
        phone: '(904) 555-0142',
        addressLine1: '1820 Magnolia Park Blvd',
        addressLine2: 'Suite 210',
        city: 'Jacksonville',
        state: 'FL',
        postalCode: '32256',
        logoUrl: 'https://placehold.co/240x80/png?text=Clover+Ridge+Dental',
        paymentTerms: 'Net 15',
        footerNote: 'Thank you for trusting PB&J Strategic Accounting with your monthly close.',
        quickbooksPayUrl: 'https://quickbooks.intuit.com/payments/example',
        invoiceShowTimeBreakdown: true,
        invoiceHideInternalHours: true,
        invoiceGroupByCategory: false,
      },
      {
        id: 'client-northstar',
        name: 'Northstar Wellness Co.',
        contact: 'Amara Stone',
        billingMode: 'subscription',
        hourlyRate: 150,
        planId: 'plan-growth',
        assignedEmployeeIds: ['emp-avery'],
        email: '',
        contactName: '',
        phone: '',
        addressLine1: '',
        addressLine2: '',
        city: '',
        state: '',
        postalCode: '',
        logoUrl: '',
        paymentTerms: '',
        footerNote: '',
        quickbooksPayUrl: '',
        invoiceShowTimeBreakdown: true,
        invoiceHideInternalHours: true,
        invoiceGroupByCategory: false,
      },
      {
        id: 'client-riverbend',
        name: 'Riverbend Market',
        contact: 'Jon Bellamy',
        billingMode: 'subscription',
        hourlyRate: 125,
        planId: 'plan-essentials',
        assignedEmployeeIds: ['emp-jordan'],
        email: '',
        contactName: '',
        phone: '',
        addressLine1: '',
        addressLine2: '',
        city: '',
        state: '',
        postalCode: '',
        logoUrl: '',
        paymentTerms: '',
        footerNote: '',
        quickbooksPayUrl: '',
        invoiceShowTimeBreakdown: true,
        invoiceHideInternalHours: true,
        invoiceGroupByCategory: false,
      },
    ],
    plans: [
      {
        id: 'plan-essentials',
        name: 'Monthly Close Essentials',
        monthlyFee: 900,
        includedHours: 8,
        notes: 'Bank feeds, reconciliations, and monthly close checklist.',
      },
      {
        id: 'plan-growth',
        name: 'Growth Advisory',
        monthlyFee: 1850,
        includedHours: 15,
        notes: 'Close support, payroll review, owner reporting, and advisory calls.',
      },
      {
        id: 'plan-payroll',
        name: 'Payroll Plus',
        monthlyFee: 520,
        includedHours: 3,
        notes: 'Payroll review, filings checklist, and exception tracking.',
      },
    ],
    timeEntries: [
      {
        id: 'time-1',
        employeeId: 'emp-avery',
        clientId: 'client-northstar',
        date: dateOffset(-1),
        minutes: 135,
        category: 'Bookkeeping',
        description: 'Reconciled operating account and reviewed uncategorized feed items.',
        billable: true,
      },
      {
        id: 'time-2',
        employeeId: 'emp-jordan',
        clientId: 'client-riverbend',
        date: dateOffset(-2),
        minutes: 75,
        category: 'Payroll',
        description: 'Checked payroll register against wage expense and benefits deductions.',
        billable: true,
      },
      {
        id: 'time-3',
        employeeId: 'emp-avery',
        clientId: 'client-clover',
        date: dateOffset(-3),
        minutes: 110,
        category: 'Cleanup',
        description: 'Reviewed dental supply vendor splits and added supporting notes.',
        billable: true,
      },
      {
        id: 'time-4',
        employeeId: 'emp-jordan',
        clientId: 'client-riverbend',
        date: dateOffset(-4),
        minutes: 35,
        category: 'Admin',
        description: 'Internal checklist prep for month-end meeting.',
        billable: false,
      },
    ],
    checklistTemplates: [
      {
        id: 'template-monthly-bookkeeping',
        title: 'Monthly Bookkeeping - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-avery',
        frequency: 'monthly',
        nextDueDate: dateOffset(-2),
        active: true,
        viewerIds: ['emp-jordan'],
        editorIds: [],
        items: [
          { id: 'template-monthly-bookkeeping-1', label: 'Clear Bank Feed - Vystar' },
          { id: 'template-monthly-bookkeeping-2', label: 'Clear Bank Feed - Amex' },
          { id: 'template-monthly-bookkeeping-3', label: 'Reconcile Books to Statements - Vystar CK' },
          { id: 'template-monthly-bookkeeping-4', label: 'Reconcile Books to Statements - Vystar SVG' },
          { id: 'template-monthly-bookkeeping-5', label: 'Reconcile Books to Statements - Vystar Loan' },
          { id: 'template-monthly-bookkeeping-6', label: 'Reconcile Books to Statements - Vystar LOC' },
          { id: 'template-monthly-bookkeeping-7', label: 'Reconcile Books to Statements - Amex' },
          { id: 'template-monthly-bookkeeping-8', label: 'Reconcile Books to Statements - Madison Trust Co' },
        ],
      },
      {
        id: 'template-quarterly-bookkeeping',
        title: 'Quarterly Bookkeeping - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-avery',
        frequency: 'quarterly',
        nextDueDate: dateOffset(70),
        active: true,
        viewerIds: [],
        editorIds: [],
        items: [
          { id: 'template-quarterly-bookkeeping-1', label: 'Clear Bank Feed - Vystar' },
          { id: 'template-quarterly-bookkeeping-2', label: 'Clear Bank Feed - Amex' },
          { id: 'template-quarterly-bookkeeping-3', label: 'Reconcile Books to Statements - Vystar CK' },
          { id: 'template-quarterly-bookkeeping-4', label: 'Reconcile Books to Statements - Vystar SVG' },
          { id: 'template-quarterly-bookkeeping-5', label: 'Reconcile Books to Statements - Vystar Loan' },
          { id: 'template-quarterly-bookkeeping-6', label: 'Reconcile Books to Statements - Vystar LOC' },
          { id: 'template-quarterly-bookkeeping-7', label: 'Review each balance sheet item matches statements' },
          { id: 'template-quarterly-bookkeeping-8', label: 'Review each account on the P&L' },
          { id: 'template-quarterly-bookkeeping-9', label: 'Send reports to client' },
          { id: 'template-quarterly-bookkeeping-10', label: 'Client call' },
        ],
      },
      {
        id: 'template-payroll',
        title: 'Payroll - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-jordan',
        frequency: 'weekly',
        nextDueDate: dateOffset(4),
        active: true,
        viewerIds: [],
        editorIds: [],
        items: [
          { id: 'template-payroll-1', label: 'Review payroll draft' },
          { id: 'template-payroll-2', label: 'Confirm payroll liabilities' },
          { id: 'template-payroll-3', label: 'Post payroll journal entry' },
        ],
      },
      {
        id: 'template-sales-tax',
        title: 'Monthly Sales Tax - CD',
        clientId: 'client-riverbend',
        assigneeId: 'emp-jordan',
        frequency: 'monthly',
        nextDueDate: dateOffset(20),
        active: true,
        viewerIds: [],
        editorIds: [],
        items: [
          { id: 'template-sales-tax-1', label: 'Pull taxable sales report' },
          { id: 'template-sales-tax-2', label: 'Review exemptions and adjustments' },
          { id: 'template-sales-tax-3', label: 'File and confirm payment' },
        ],
      },
      {
        id: 'template-1099',
        title: '1099 Preparation - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-patrice',
        frequency: 'annually',
        nextDueDate: '2026-11-30',
        active: true,
        viewerIds: [],
        editorIds: [],
        items: [
          { id: 'template-1099-1', label: 'Review GL for payments made to vendors' },
          { id: 'template-1099-2', label: 'Review GL after final transactions added for YE' },
          { id: 'template-1099-3', label: 'Send 1099 list to client for approval' },
          { id: 'template-1099-4', label: 'Prepare and send 1099s' },
        ],
      },
    ],
    checklists: [],
  }
}
