import type { AppData } from './types'
import { dateOffset } from './utils'

/**
 * Empty workspace shape for React state initialization BEFORE the real
 * workspace is fetched from the server. Using the rich `createSeedData`
 * blueprint for that role made the UI flash demo clients / templates /
 * checklists on every reload until the fetch resolved — which made
 * just-deleted items briefly reappear. The empty shape renders nothing
 * instead.
 */
export function createEmptyAppData(): AppData {
  return {
    employees: [],
    clients: [],
    plans: [],
    contacts: [],
    timeEntries: [],
    checklistTemplates: [],
    checklists: [],
    recycledChecklists: [],
    timesheetLocks: [],
    weeklySubmissions: [],
    reimbursements: [],
    recurringReimbursements: [],
    inactiveEmployees: [],
  }
}

export function createSeedData(): AppData {
  return {
    employees: [
      { id: 'emp-avery', name: 'Avery Johnson', role: 'Accountant' },
      { id: 'emp-jordan', name: 'Jordan Ellis', role: 'Bookkeeper' },
      { id: 'emp-patrice', name: 'Brittany Ferguson', role: 'Owner' },
    ],
    clients: [
      {
        id: 'client-clover',
        name: 'Clover Ridge Dental',
        contact: 'Dr. Maya Kent',
        billingMode: 'hourly',
        hourlyRate: 145,
        planIds: [],
        contactIds: ['contact-maya'],
        estimatedBookkeeperHours: 4,
        estimatedAccountantHours: 2,
        estimatedCfoHours: 0,
        assignedEmployeeIds: ['emp-avery'],
        assignedBookkeeperIds: ['emp-avery', 'emp-jordan'],
        email: 'billing@cloverridgedental.example',
        contactName: 'Dr. Maya Kent',
        phone: '(904) 555-0142',
        addressLine1: '1820 Magnolia Park Blvd',
        addressLine2: 'Suite 210',
        city: 'Jacksonville',
        state: 'FL',
        postalCode: '32256',
        logoUrl: 'https://placehold.co/240x80/png?text=Clover+Ridge+Dental',
        paymentTerms: 'Net 15',
        footerNote: 'Thank you for trusting PB&J Strategic Accounting with your monthly close.',
        quickbooksPayUrl: 'https://quickbooks.intuit.com/payments/example',
        invoiceShowTimeBreakdown: true,
        invoiceHideInternalHours: true,
        invoiceGroupByCategory: false,
      },
      {
        id: 'client-northstar',
        name: 'Northstar Wellness Co.',
        contact: 'Amara Stone',
        billingMode: 'subscription',
        hourlyRate: 150,
        planIds: ['plan-growth'],
        monthlyRate: 1850,
        estimatedBookkeeperHours: 8,
        estimatedAccountantHours: 4,
        estimatedCfoHours: 3,
        contactIds: ['contact-amara'],
        assignedEmployeeIds: ['emp-avery'],
        assignedBookkeeperIds: ['emp-avery'],
        email: '',
        contactName: '',
        phone: '',
        addressLine1: '',
        addressLine2: '',
        city: '',
        state: '',
        postalCode: '',
        logoUrl: '',
        paymentTerms: '',
        footerNote: '',
        quickbooksPayUrl: '',
        invoiceShowTimeBreakdown: true,
        invoiceHideInternalHours: true,
        invoiceGroupByCategory: false,
      },
      {
        id: 'client-riverbend',
        name: 'Riverbend Market',
        contact: 'Jon Bellamy',
        billingMode: 'subscription',
        hourlyRate: 125,
        planIds: ['plan-essentials', 'plan-payroll'],
        monthlyRate: 900,
        estimatedBookkeeperHours: 5,
        estimatedAccountantHours: 2,
        estimatedCfoHours: 1,
        contactIds: ['contact-jon'],
        assignedEmployeeIds: ['emp-jordan'],
        assignedBookkeeperIds: ['emp-jordan'],
        email: '',
        contactName: '',
        phone: '',
        addressLine1: '',
        addressLine2: '',
        city: '',
        state: '',
        postalCode: '',
        logoUrl: '',
        paymentTerms: '',
        footerNote: '',
        quickbooksPayUrl: '',
        invoiceShowTimeBreakdown: true,
        invoiceHideInternalHours: true,
        invoiceGroupByCategory: false,
      },
    ],
    plans: [
      {
        id: 'plan-essentials',
        name: 'Monthly Close Essentials',
        notes: 'Bank feeds, reconciliations, and monthly close checklist.',
      },
      {
        id: 'plan-growth',
        name: 'Growth Advisory',
        notes: 'Close support, payroll review, owner reporting, and advisory calls.',
      },
      {
        id: 'plan-payroll',
        name: 'Payroll Plus',
        notes: 'Payroll review, filings checklist, and exception tracking.',
      },
    ],
    contacts: [
      {
        id: 'contact-maya',
        name: 'Dr. Maya Kent',
        email: 'maya@cloverridgedental.example',
        phone: '(904) 555-0142',
        title: 'Owner / Dentist',
        notes: 'Primary contact for the monthly close package.',
      },
      {
        id: 'contact-amara',
        name: 'Amara Stone',
        email: 'amara@northstarwellness.example',
        phone: '(904) 555-0188',
        title: 'Operations Director',
        notes: '',
      },
      {
        id: 'contact-jon',
        name: 'Jon Bellamy',
        email: 'jon@riverbendmarket.example',
        phone: '(904) 555-0199',
        title: 'Owner',
        notes: '',
      },
    ],
    timeEntries: [
      {
        id: 'time-1',
        employeeId: 'emp-avery',
        clientId: 'client-northstar',
        date: dateOffset(-1),
        minutes: 135,
        description: 'Reconciled operating account and reviewed uncategorized feed items.',
        billable: true,
        approvalStatus: 'approved',
        entryMethod: 'timer',
      },
      {
        id: 'time-2',
        employeeId: 'emp-jordan',
        clientId: 'client-riverbend',
        date: dateOffset(-2),
        minutes: 75,
        description: 'Checked payroll register against wage expense and benefits deductions.',
        billable: true,
        approvalStatus: 'approved',
        entryMethod: 'timer',
      },
      {
        id: 'time-3',
        employeeId: 'emp-avery',
        clientId: 'client-clover',
        date: dateOffset(-3),
        minutes: 110,
        description: 'Reviewed dental supply vendor splits and added supporting notes.',
        billable: true,
        approvalStatus: 'approved',
        entryMethod: 'timer',
      },
      {
        id: 'time-4',
        employeeId: 'emp-jordan',
        clientId: 'client-riverbend',
        date: dateOffset(-4),
        minutes: 35,
        description: 'Internal checklist prep for month-end meeting.',
        billable: false,
        approvalStatus: 'approved',
        entryMethod: 'timer',
      },
    ],
    checklistTemplates: [
      {
        id: 'template-monthly-bookkeeping',
        title: 'Monthly Bookkeeping - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-avery',
        frequency: 'monthly',
        nextDueDate: dateOffset(-2),
        active: true,
        viewerIds: ['emp-jordan'],
        editorIds: [],
        stages: [
          {
            id: 'stage-monthly-data-entry',
            name: 'Data Entry',
            assigneeId: 'emp-avery',
            offsetDays: 0,
            viewerIds: ['emp-jordan'],
            editorIds: [],
            items: [
              { id: 'template-monthly-bookkeeping-1', label: 'Clear Bank Feed - Vystar' },
              { id: 'template-monthly-bookkeeping-2', label: 'Clear Bank Feed - Amex' },
              { id: 'template-monthly-bookkeeping-3', label: 'Reconcile Books to Statements - Vystar CK' },
            ],
          },
          {
            id: 'stage-monthly-review',
            name: 'Review',
            assigneeId: 'emp-jordan',
            offsetDays: 2,
            viewerIds: ['emp-avery'],
            editorIds: [],
            items: [
              { id: 'template-monthly-bookkeeping-4', label: 'Review balance sheet ties to statements' },
              { id: 'template-monthly-bookkeeping-5', label: 'Review P&L for unusual variances' },
              { id: 'template-monthly-bookkeeping-6', label: 'Confirm reconciliations clean' },
            ],
          },
          {
            id: 'stage-monthly-signoff',
            name: 'Owner Sign-off',
            assigneeId: 'emp-patrice',
            offsetDays: 2,
            viewerIds: ['emp-avery', 'emp-jordan'],
            editorIds: [],
            items: [
              { id: 'template-monthly-bookkeeping-7', label: 'Final review of month-end package' },
              { id: 'template-monthly-bookkeeping-8', label: 'Send report to client' },
            ],
          },
        ],
      },
      {
        id: 'template-quarterly-bookkeeping',
        title: 'Quarterly Bookkeeping - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-avery',
        frequency: 'quarterly',
        nextDueDate: dateOffset(70),
        active: true,
        viewerIds: [],
        editorIds: [],
        stages: [
          {
            id: 'stage-quarterly-1',
            name: 'Stage 1',
            assigneeId: 'emp-avery',
            offsetDays: 0,
            viewerIds: [],
            editorIds: [],
            items: [
              { id: 'template-quarterly-bookkeeping-1', label: 'Clear Bank Feed - Vystar' },
              { id: 'template-quarterly-bookkeeping-2', label: 'Clear Bank Feed - Amex' },
              { id: 'template-quarterly-bookkeeping-3', label: 'Reconcile Books to Statements - Vystar CK' },
              { id: 'template-quarterly-bookkeeping-4', label: 'Reconcile Books to Statements - Vystar SVG' },
              { id: 'template-quarterly-bookkeeping-5', label: 'Reconcile Books to Statements - Vystar Loan' },
              { id: 'template-quarterly-bookkeeping-6', label: 'Reconcile Books to Statements - Vystar LOC' },
              { id: 'template-quarterly-bookkeeping-7', label: 'Review each balance sheet item matches statements' },
              { id: 'template-quarterly-bookkeeping-8', label: 'Review each account on the P&L' },
              { id: 'template-quarterly-bookkeeping-9', label: 'Send reports to client' },
              { id: 'template-quarterly-bookkeeping-10', label: 'Client call' },
            ],
          },
        ],
      },
      {
        id: 'template-payroll',
        title: 'Payroll - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-jordan',
        frequency: 'weekly',
        nextDueDate: dateOffset(4),
        active: true,
        viewerIds: [],
        editorIds: [],
        stages: [
          {
            id: 'stage-payroll-1',
            name: 'Stage 1',
            assigneeId: 'emp-jordan',
            offsetDays: 0,
            viewerIds: [],
            editorIds: [],
            items: [
              { id: 'template-payroll-1', label: 'Review payroll draft' },
              { id: 'template-payroll-2', label: 'Confirm payroll liabilities' },
              { id: 'template-payroll-3', label: 'Post payroll journal entry' },
            ],
          },
        ],
      },
      {
        id: 'template-sales-tax',
        title: 'Monthly Sales Tax - CD',
        clientId: 'client-riverbend',
        assigneeId: 'emp-jordan',
        frequency: 'monthly',
        nextDueDate: dateOffset(20),
        active: true,
        viewerIds: [],
        editorIds: [],
        stages: [
          {
            id: 'stage-sales-tax-1',
            name: 'Stage 1',
            assigneeId: 'emp-jordan',
            offsetDays: 0,
            viewerIds: [],
            editorIds: [],
            items: [
              { id: 'template-sales-tax-1', label: 'Pull taxable sales report' },
              { id: 'template-sales-tax-2', label: 'Review exemptions and adjustments' },
              { id: 'template-sales-tax-3', label: 'File and confirm payment' },
            ],
          },
        ],
      },
      {
        id: 'template-1099',
        title: '1099 Preparation - CD',
        clientId: 'client-clover',
        assigneeId: 'emp-patrice',
        frequency: 'annually',
        nextDueDate: '2026-11-30',
        active: true,
        viewerIds: [],
        editorIds: [],
        stages: [
          {
            id: 'stage-1099-1',
            name: 'Stage 1',
            assigneeId: 'emp-patrice',
            offsetDays: 0,
            viewerIds: [],
            editorIds: [],
            items: [
              { id: 'template-1099-1', label: 'Review GL for payments made to vendors' },
              { id: 'template-1099-2', label: 'Review GL after final transactions added for YE' },
              { id: 'template-1099-3', label: 'Send 1099 list to client for approval' },
              { id: 'template-1099-4', label: 'Prepare and send 1099s' },
            ],
          },
        ],
      },
    ],
    checklists: [],
    recycledChecklists: [],
    timesheetLocks: [],
    weeklySubmissions: [],
    reimbursements: [],
    recurringReimbursements: [],
    inactiveEmployees: [],
  }
}
