import { useAppContext } from '../AppContext'

// Print-only header block. Hidden in normal page flow (display: none) and
// shown by `@media print` rules. Renders firm branding + report metadata so
// every printed report carries identifiable provenance.
export function PrintHeader({
  title,
  subtitle,
}: {
  title: string
  subtitle?: string
}) {
  const { firmSettings, sessionUser } = useAppContext()
  const firmName = firmSettings?.name || 'PB&J Strategic Accounting'
  const firmTagline = firmSettings?.tagline || ''
  const addressLines = [
    firmSettings?.addressLine1,
    firmSettings?.addressLine2,
    [firmSettings?.city, firmSettings?.state, firmSettings?.postalCode]
      .filter((part) => part && part.trim())
      .join(', '),
  ].filter((line) => line && line.trim().length > 0) as string[]

  const today = new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  }).format(new Date())

  return (
    <header className="print-header" aria-hidden="true">
      <div className="print-header-firm">
        {firmSettings?.logoUrl ? (
          <img alt={`${firmName} logo`} className="print-header-logo" src={firmSettings.logoUrl} />
        ) : null}
        <div className="print-header-firm-text">
          <strong>{firmName}</strong>
          {firmTagline ? <span>{firmTagline}</span> : null}
          {addressLines.map((line) => (
            <span key={line}>{line}</span>
          ))}
        </div>
      </div>
      <div className="print-header-report">
        <h2>{title}</h2>
        {subtitle ? <p>{subtitle}</p> : null}
        <p className="print-header-meta">
          Generated by {sessionUser?.name ?? 'unknown user'} on {today}
        </p>
      </div>
    </header>
  )
}
